export const SELECTED_CUSTOM_JOB_POST = "SELECTED_CUSTOM_JOB_POST";
export const CUSTOM_APPLY_SAVED_JOB = "CUSTOM_APPLY_SAVED_JOB";
export const RESPOND_TO_FRIEND_REQUEST = "RESPOND_TO_FRIEND_REQUEST";
