export const SELECTED_CUSTOM_JOB_POST = "SELECTED_CUSTOM_JOB_POST";
export const CUSTOM_APPLY_SAVED_JOB = "CUSTOM_APPLY_SAVED_JOB";
export const UPDATED_JOB_SEARCH_CRITERIA = "UPDATED_JOB_SEARCH_CRITERIA";
export const ADD_JOB_ID_TO_APPLIED_JOB = "ADD_JOB_ID_TO_APPLIED_JOB";
export const ADD_JOB_ID_TO_SAVED_JOB = "ADD_JOB_ID_TO_SAVED_JOB";
export const RESPOND_TO_FRIEND_REQUEST = "RESPOND_TO_FRIEND_REQUEST";
